import React from "react";

const columns = [
  { name: "Card", uid: "card", sortable: true },
  { name: "Cashback", uid: "cashback", sortable: true },
  { name: "Credit Score", uid: "credit_score", sortable: true },
  { name: "Rating", uid: "rating", sortable: true },
];

const cards = [
  {
    id: 1,
    card: "Freedom Unlimited",
    issuer: "Chase",
    cashback: "1.5%",
    credit_score: 700,
    rating: 3.0,
    reviews: 1234,
  },
  {
    id: 2,
    card: "Double Cash",
    issuer: "Citi",
    cashback: "2%",
    credit_score: 720,
    rating: 4.0,
    reviews: 5678,
  },
  {
    id: 3,
    card: "Blue Cash Preferred",
    issuer: "American Express",
    cashback: "6%",
    credit_score: 750,
    rating: 5.0,
    reviews: 12345,
  },
  {
    id: 4,
    card: "SavorOne Cash Rewards",
    issuer: "Capital One",
    cashback: "3%",
    credit_score: 680,
    rating: 3.5,
    reviews: 2382,
  },
  {
    id: 5,
    card: "Amex EveryDay Preferred",
    issuer: "American Express",
    cashback: "3%",
    credit_score: 670,
    rating: 4.2,
    reviews: 8765,
  },
  {
    id: 6,
    card: "Venture Rewards",
    issuer: "Capital One",
    cashback: "2%",
    credit_score: 690,
    rating: 4.5,
    reviews: 6789,
  },
  {
    id: 7,
    card: "Cash Magnet",
    issuer: "American Express",
    cashback: "1.5%",
    credit_score: 710,
    rating: 4.1,
    reviews: 3456,
  },
  {
    id: 8,
    card: "Quicksilver",
    issuer: "Capital One",
    cashback: "1.5%",
    credit_score: 680,
    rating: 3.8,
    reviews: 2345,
  },
  {
    id: 9,
    card: "Discover it",
    issuer: "Discover",
    cashback: "5%",
    credit_score: 720,
    rating: 4.7,
    reviews: 7890,
  },
  {
    id: 10,
    card: "Platinum Card",
    issuer: "American Express",
    cashback: "1%",
    credit_score: 750,
    rating: 4.9,
    reviews: 4567,
  },
  {
    id: 11,
    card: "Gold Card",
    issuer: "American Express",
    cashback: "4%",
    credit_score: 740,
    rating: 4.8,
    reviews: 5678,
  },
  {
    id: 12,
    card: "Green Card",
    issuer: "American Express",
    cashback: "3%",
    credit_score: 730,
    rating: 4.3,
    reviews: 3456,
  },
  {
    id: 13,
    card: "Blue Cash Everyday",
    issuer: "American Express",
    cashback: "3%",
    credit_score: 720,
    rating: 4.2,
    reviews: 2345,
  },
  {
    id: 14,
    card: "Citi Rewards+",
    issuer: "Citi",
    cashback: "2%",
    credit_score: 710,
    rating: 4.0,
    reviews: 1234,
  },
  {
    id: 15,
    card: "Custom Cash",
    issuer: "Citi",
    cashback: "5%",
    credit_score: 700,
    rating: 4.5,
    reviews: 5678,
  },
  {
    id: 16,
    card: "Simplicity",
    issuer: "Citi",
    cashback: "1%",
    credit_score: 690,
    rating: 3.9,
    reviews: 2345,
  },
  {
    id: 17,
    card: "Diamond Preferred",
    issuer: "Citi",
    cashback: "1%",
    credit_score: 680,
    rating: 3.7,
    reviews: 1234,
  },
  {
    id: 18,
    card: "Premier",
    issuer: "Citi",
    cashback: "3%",
    credit_score: 720,
    rating: 4.6,
    reviews: 4567,
  },
  {
    id: 19,
    card: "Prestige",
    issuer: "Citi",
    cashback: "5%",
    credit_score: 750,
    rating: 4.9,
    reviews: 6789,
  },
  {
    id: 20,
    card: "Altitude Reserve",
    issuer: "U.S. Bank",
    cashback: "3%",
    credit_score: 740,
    rating: 4.8,
    reviews: 3456,
  },
  {
    id: 21,
    card: "Cash+",
    issuer: "U.S. Bank",
    cashback: "5%",
    credit_score: 720,
    rating: 4.7,
    reviews: 2345,
  },
  {
    id: 22,
    card: "Platinum",
    issuer: "U.S. Bank",
    cashback: "1%",
    credit_score: 700,
    rating: 4.0,
    reviews: 1234,
  },
  {
    id: 23,
    card: "Visa Signature",
    issuer: "U.S. Bank",
    cashback: "2%",
    credit_score: 710,
    rating: 4.1,
    reviews: 3456,
  },
  {
    id: 24,
    card: "FlexPerks",
    issuer: "U.S. Bank",
    cashback: "3%",
    credit_score: 720,
    rating: 4.3,
    reviews: 4567,
  },
  {
    id: 25,
    card: "Altitude Go",
    issuer: "U.S. Bank",
    cashback: "4%",
    credit_score: 730,
    rating: 4.5,
    reviews: 5678,
  },
  {
    id: 26,
    card: "Cash Rewards",
    issuer: "Bank of America",
    cashback: "3%",
    credit_score: 700,
    rating: 4.2,
    reviews: 2345,
  },
  {
    id: 27,
    card: "Travel Rewards",
    issuer: "Bank of America",
    cashback: "1.5%",
    credit_score: 710,
    rating: 4.0,
    reviews: 1234,
  },
  {
    id: 28,
    card: "Premium Rewards",
    issuer: "Bank of America",
    cashback: "2%",
    credit_score: 720,
    rating: 4.3,
    reviews: 3456,
  },
  {
    id: 29,
    card: "Unlimited Cash Rewards",
    issuer: "Bank of America",
    cashback: "1.5%",
    credit_score: 700,
    rating: 4.1,
    reviews: 2345,
  },
  {
    id: 30,
    card: "Customized Cash Rewards",
    issuer: "Bank of America",
    cashback: "3%",
    credit_score: 710,
    rating: 4.4,
    reviews: 4567,
  },
  {
    id: 31,
    card: "Secured",
    issuer: "Bank of America",
    cashback: "1%",
    credit_score: 680,
    rating: 3.8,
    reviews: 1234,
  },
  {
    id: 32,
    card: "Platinum Plus",
    issuer: "Bank of America",
    cashback: "1%",
    credit_score: 690,
    rating: 3.9,
    reviews: 2345,
  },
  {
    id: 33,
    card: "Cash Rewards for Students",
    issuer: "Bank of America",
    cashback: "3%",
    credit_score: 700,
    rating: 4.2,
    reviews: 3456,
  },
  {
    id: 34,
    card: "Travel Rewards for Students",
    issuer: "Bank of America",
    cashback: "1.5%",
    credit_score: 710,
    rating: 4.0,
    reviews: 1234,
  },
  {
    id: 35,
    card: "Premium Rewards Elite",
    issuer: "Bank of America",
    cashback: "2%",
    credit_score: 720,
    rating: 4.5,
    reviews: 4567,
  },
  {
    id: 36,
    card: "Cash Rewards for Business",
    issuer: "Bank of America",
    cashback: "3%",
    credit_score: 700,
    rating: 4.3,
    reviews: 2345,
  },
  {
    id: 37,
    card: "Travel Rewards for Business",
    issuer: "Bank of America",
    cashback: "1.5%",
    credit_score: 710,
    rating: 4.1,
    reviews: 1234,
  },
  {
    id: 38,
    card: "Business Advantage Cash Rewards",
    issuer: "Bank of America",
    cashback: "3%",
    credit_score: 720,
    rating: 4.4,
    reviews: 3456,
  },
  {
    id: 39,
    card: "Business Advantage Travel Rewards",
    issuer: "Bank of America",
    cashback: "1.5%",
    credit_score: 700,
    rating: 4.0,
    reviews: 2345,
  },
  {
    id: 40,
    card: "Business Advantage Unlimited Cash Rewards",
    issuer: "Bank of America",
    cashback: "1.5%",
    credit_score: 710,
    rating: 4.2,
    reviews: 1234,
  },
  {
    id: 41,
    card: "Business Advantage Customized Cash Rewards",
    issuer: "Bank of America",
    cashback: "3%",
    credit_score: 720,
    rating: 4.5,
    reviews: 3456,
  },
  {
    id: 42,
    card: "Business Advantage Secured",
    issuer: "Bank of America",
    cashback: "1%",
    credit_score: 680,
    rating: 3.8,
    reviews: 2345,
  },
  {
    id: 43,
    card: "Business Advantage Platinum Plus",
    issuer: "Bank of America",
    cashback: "1%",
    credit_score: 690,
    rating: 3.9,
    reviews: 1234,
  },
  {
    id: 44,
    card: "Business Advantage Cash Rewards for Students",
    issuer: "Bank of America",
    cashback: "3%",
    credit_score: 700,
    rating: 4.2,
    reviews: 3456,
  },
  {
    id: 45,
    card: "Business Advantage Travel Rewards for Students",
    issuer: "Bank of America",
    cashback: "1.5%",
    credit_score: 710,
    rating: 4.0,
    reviews: 1234,
  },
  {
    id: 46,
    card: "Business Advantage Premium Rewards Elite",
    issuer: "Bank of America",
    cashback: "2%",
    credit_score: 720,
    rating: 4.5,
    reviews: 4567,
  },
  {
    id: 47,
    card: "Business Advantage Cash Rewards for Business",
    issuer: "Bank of America",
    cashback: "3%",
    credit_score: 700,
    rating: 4.3,
    reviews: 2345,
  },
  {
    id: 48,
    card: "Business Advantage Travel Rewards for Business",
    issuer: "Bank of America",
    cashback: "1.5%",
    credit_score: 710,
    rating: 4.1,
    reviews: 1234,
  },
  {
    id: 49,
    card: "Business Advantage Unlimited Cash Rewards for Business",
    issuer: "Bank of America",
    cashback: "1.5%",
    credit_score: 720,
    rating: 4.4,
    reviews: 3456,
  },
  {
    id: 50,
    card: "Business Advantage Customized Cash Rewards for Business",
    issuer: "Bank of America",
    cashback: "3%",
    credit_score: 700,
    rating: 4.5,
    reviews: 2345,
  },
];

export { columns, cards };
