import React, { useEffect, useState } from "react";
import { Spinner } from "@nextui-org/react";
import { IconRobot } from "@tabler/icons-react";
import { cn } from "./cn";
import { useApi } from "../../../../hooks/useApi";
import MessageCard from "../../../CARDPAGE/from-the-web/message-card";

const AISummaryCard = React.forwardRef(
  (
    { className, cardId, ...props },
    ref
  ) => {
    const [summary, setSummary] = useState("");
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const api = useApi();
    useEffect(() => {
      const fetchSummary = async () => {
        if (!cardId) return;

        try {
          setLoading(true);
          const response = await api.getCardAISummary(cardId);
          setSummary(response.data.summary);
          setError(null);
        } catch (err) {
          console.error("Error fetching AI summary:", err);
          setError("Unable to generate summary.");
        } finally {
          setLoading(false);
        }
      };

      fetchSummary();
    }, [cardId, api]);

    const robotAvatar = "https://cdn-icons-png.flaticon.com/512/4712/4712027.png"; // AI robot avatar URL

    const renderMessage = () => {
      if (loading) {
        return (
          <div className="flex justify-center items-center py-4">
            <Spinner color="primary" />
          </div>
        );
      }

      if (error) {
        return <div className="text-danger">{error}</div>;
      }

      return (
        <>
          {summary}
          <div className="mt-4 text-tiny text-default-400 italic">
            This summary is generated by AI based on card details and user reviews.
            It may not be completely accurate or reflect all opinions.
          </div>
        </>
      );
    };

    return (
      <MessageCard
        ref={ref}
        avatar={robotAvatar}
        message={renderMessage()}
        className={cn("w-full", className)}
        messageClassName="whitespace-pre-line"
        {...props}
      />
    );
  }
);

AISummaryCard.displayName = "AISummaryCard";

export default AISummaryCard;
