import React, { useEffect, useState } from "react";
import { Card, CardBody, Spinner } from "@nextui-org/react";
import { IconRobot } from "@tabler/icons-react";
import { cn } from "./cn";
import { useApi } from "../../../../hooks/useApi";

const AISummaryCard = React.forwardRef(
  (
    { className, cardId, ...props },
    ref
  ) => {
    const [summary, setSummary] = useState("");
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const api = useApi();
    useEffect(() => {
      const fetchSummary = async () => {
        if (!cardId) return;

        try {
          setLoading(true);
          const response = await api.getCardAISummary(cardId);
          setSummary(response.data.summary);
          setError(null);
        } catch (err) {
          console.error("Error fetching AI summary:", err);
          setError("Unable to generate summary.");
        } finally {
          setLoading(false);
        }
      };

      fetchSummary();
    }, [cardId, api]);

    return (
      <Card
        ref={ref}
        className={cn(
          "w-full shadow-small",
          className
        )}
        {...props}
      >
        <CardBody>
          <div className="flex items-center gap-2 mb-2">
            <IconRobot className="text-primary" />
            <h3 className="text-lg font-semibold">AI-Generated Summary</h3>
          </div>

          {loading ? (
            <div className="flex justify-center items-center py-8">
              <Spinner color="primary" />
            </div>
          ) : error ? (
            <div className="text-danger py-2">{error}</div>
          ) : (
            <div className="text-default-700 whitespace-pre-line">
              {summary}
            </div>
          )}

          {!loading && (
            <div className="mt-4 text-tiny text-default-400 italic">
              This summary is generated by AI based on card details and user reviews.
              It may not be completely accurate or reflect all opinions.
            </div>
          )}
        </CardBody>
      </Card>
    );
  }
);

AISummaryCard.displayName = "AISummaryCard";

export default AISummaryCard;
